version: "3.3"
services:
    apiserver:
        build:
            context: ./
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"